spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev  #开发环境
  application:
    name: microservicecloud-config-jander-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-jander-test